"""Generate the checked-in smoke table from a real local ExperimentReport."""

from __future__ import annotations

import argparse
from pathlib import Path

from langres.experiments import EvaluationProtocol, Experiment, ExperimentReport

from _research_foundation import retrieve_factory


def build_report(output_dir: Path) -> ExperimentReport:
    """Run two deterministic fake-resource architectures on the tiny fixture."""
    output_dir.mkdir(parents=True, exist_ok=True)
    return Experiment(
        architectures=(
            retrieve_factory(),
            retrieve_factory(name="RetrieveRerank", rerank=True),
        ),
        protocol=EvaluationProtocol.smoke(seed=0),
        store=output_dir / "runs.jsonl",
        cache_dir=output_dir / "stage-cache",
        budget_usd=0.0,
        resume=False,
    ).run()


def render(report: ExperimentReport) -> str:
    """Render generated evidence with a provenance warning."""
    return (
        "<!-- Generated by examples/research/generate_smoke_table.py; do not edit. -->\n\n"
        "This table is a contract smoke test over deterministic fake resources. "
        "It is not a model-quality claim or a comparison with external systems.\n\n"
        f"{report.to_markdown()}\n"
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("docs/generated/research_smoke_table.md"),
    )
    parser.add_argument("--run-dir", type=Path, default=Path("runs/docs-smoke-table"))
    args = parser.parse_args()
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(render(build_report(args.run_dir)))
    print(f"wrote {args.output}")


if __name__ == "__main__":
    main()
