"""Offline smoke coverage for the research-foundation copy-paste examples."""

from __future__ import annotations

import importlib.util
import subprocess
import sys
from pathlib import Path
from types import ModuleType

from langres.experiments import expand_official_proof_matrix

ROOT = Path(__file__).parents[2]
RESEARCH = ROOT / "examples" / "research"


def _load(name: str, path: Path) -> ModuleType:
    sys.path.insert(0, str(path.parent))
    try:
        spec = importlib.util.spec_from_file_location(name, path)
        assert spec is not None and spec.loader is not None
        module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(module)
        return module
    finally:
        sys.path.remove(str(path.parent))


def test_all_four_recipe_examples_run_without_network() -> None:
    module = _load("example_research_recipes", ROOT / "examples" / "research_recipes.py")

    recipes = module.build_recipes()
    clusters = {name: list(recipe.dedupe(module.RECORDS)) for name, recipe in recipes.items()}

    assert set(recipes) == {
        "Retrieve",
        "RetrieveRerank",
        "RetrieveLLM",
        "RetrieveRerankLLM",
    }
    assert {"a", "b"} in clusters["RetrieveRerank"]
    assert {"a", "b"} in clusters["RetrieveLLM"]
    assert {"a", "b"} in clusters["RetrieveRerankLLM"]


def test_embedding_separability_example_measures_a_margin() -> None:
    module = _load(
        "example_embedding_separability",
        ROOT / "examples" / "embedding_separability.py",
    )

    margin = module.separability_margin(module.FakeEmbedder(dimension=32))

    assert margin > 0.0


def test_first_experiment_and_generated_table_use_real_reports(tmp_path: Path) -> None:
    first = _load("example_first_experiment", RESEARCH / "first_experiment.py")
    generator = _load("example_generate_smoke_table", RESEARCH / "generate_smoke_table.py")

    first_report = first.run_first_experiment(tmp_path / "first")
    smoke_report = generator.build_report(tmp_path / "table")
    rendered = generator.render(smoke_report)

    assert [run.status for run in first_report.runs] == ["completed"]
    assert len(smoke_report.runs) == 2
    assert all(run.status == "completed" for run in smoke_report.runs)
    assert "Generated by examples/research/generate_smoke_table.py" in rendered
    assert "| RetrieveRerank |" in rendered


def test_matrix_and_paid_proof_plans_are_exact_without_execution() -> None:
    matrix = _load("example_experiment_matrix", RESEARCH / "experiment_matrix.py")
    paid = _load("example_official_paid_proof", RESEARCH / "official_paid_proof.py")

    protocol = matrix.build_protocol()
    proof = paid.build_protocol()

    assert (
        2
        * len(protocol.benchmark_ids)
        * len(protocol.split_ids)
        * len(protocol.split_seeds)
        == 16
    )
    assert len(expand_official_proof_matrix(proof)) == 18
    assert proof.budget_usd == 20.0
    assert paid.PAID_CONCURRENCY == 1


def test_local_hub_round_trip_needs_no_hub_client(tmp_path: Path) -> None:
    module = _load("example_hub_lifecycle", RESEARCH / "hub_lifecycle.py")

    loaded = module.local_round_trip(tmp_path / "bundle")

    assert type(loaded).__name__ == "FuzzyString"
    assert loaded.clusterer.threshold == 0.7


def test_example_modules_are_import_light() -> None:
    script = """
import runpy
import sys
paths = [
    "examples/embedding_separability.py",
    "examples/research_recipes.py",
    "examples/research/first_experiment.py",
    "examples/research/experiment_matrix.py",
    "examples/research/trackio_reproduction.py",
    "examples/research/reprice_tokens.py",
    "examples/research/hub_lifecycle.py",
    "examples/research/official_paid_proof.py",
]
sys.path.insert(0, "examples/research")
for path in paths:
    runpy.run_path(path, run_name="import_check")
heavy = {"torch", "faiss", "litellm", "trackio", "huggingface_hub"}
assert heavy.isdisjoint(sys.modules), heavy.intersection(sys.modules)
"""
    completed = subprocess.run(
        [sys.executable, "-c", script],
        cwd=ROOT,
        check=False,
        capture_output=True,
        text=True,
    )

    assert completed.returncode == 0, completed.stderr
